apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "100"
    kubectl.kubernetes.io/last-applied-configuration: |
  generation: 102
  labels:
    app: makalu-hrm
    app-process-type: makalu-hrm-web
    process-type: web
  name: makalu-hrm-web
  namespace: default
  resourceVersion: "125648747"
  uid: 58f463a4-f9b3-468b-9c50-3ebd488cce4e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: makalu-hrm
      app-process-type: makalu-hrm-web
      process-type: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-12-15T16:05:39Z"
      creationTimestamp: null
      labels:
        app: makalu-hrm
        app-process-type: makalu-hrm-web
        process-type: web
    spec:
      containers:
        - env:
            - name: PORT
              value: "5000"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: dhirajbadu/makalu-hrm:latest
          imagePullPolicy: Always
          name: makalu-hrm-web
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30